### ISSUE TITLE
ResourceGroup conditional resources

### ISSUE THREAD

**Issue by a-hilaly** [awslabs/kro#15]
Add support for conditional resource creation in `ResourceGroups` allowing resources to be created only when specified conditions are met.

- Implement condition specification using CEL expressions
- Allow referencing of spec fields and other contextual information in conditions
- Add condition evaluation during the reconciliation process

Conditional example (still not decided on the field name and type):
```yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: conditionalExample.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: ConditionalExample
  definition:
    spec:
      enabled: 
  resources:
  - name: service
    conditional:
    - ${spec.enabled}
    - ${123 > 100 && 123 < 200}
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: myservice
      spec: {}
```

**Comment by michaelhtm** [comment]
We can extend this feature and support conditional fields, allowing for certain fields to be null when specified conditions are not met. 

An example 
```yaml
metadata:
  name: ${spec.name}
  namespace: ${if(spec.namespace != "", spec.namespace, null)}
```
