### ISSUE TITLE
[feat] - Add support for helper functions/definitions  to avoid repetitions

### ISSUE THREAD

**Issue by tsahiduek** [awslabs/kro#158]
### Feature Description

**Problem Statement**:

Keep my configuration DRY.
When defining values that are combined from 2 different parameters in the Scheme section, I would like to define this value once, and then reuse it for the rest of my config.
For example, when defining an Ingress object which input both `customDomain` (e.g. `app1) and `baseDomain` (e.g. `example.com`), currently I need to repeat the `${schema.spec.customDomain.id}.${schema.spec.baseDomain}` in multiple locations in the ingress. See example below:

```yaml
  resources:
    - id: url
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ${schema.spec.appName}
        namespace: ${schema.spec.namespace}
        annotations:
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/target-type: ip
          external-dns.alpha.kubernetes.io/hostname: `${schema.spec.customDomain.id}.${schema.spec.baseDomain}` 
          external-dns.alpha.kubernetes.io/ttl: "60"
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
          alb.ingress.kubernetes.io/ssl-redirect: '443'
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
          alb.ingress.kubernetes.io/group.name: standard
      spec:
        ingressClassName: alb
        tls:
        - hosts:
          - `${schema.spec.customDomain.id}.${schema.spec.baseDomain}` 
        rules:
          - host: `${schema.spec.customDomain.id}.${schema.spec.baseDomain}` 
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: service
                      port: 
                        number: 80

```

**Proposed Solution**:

Be able to define a spec field that is calculated from other fields, and reuse it:
`$schema.spec.fullDomain := ${schema.spec.customDomain.id}.${schema.spec.baseDomain}` 

**Alternatives Considered**:

Calculating this value outside of the resourceGroup (with helm as one option), or repeating the config throughout the resourceGroup definition

**Additional Context**:

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment

**Comment by mrwulf** [comment]
Another implementation option, allow `default` to reference other fields
```
spec:
  fullDomain: string | default="${schema.spec.customDomain.id}.${schema.spec.baseDomain}"
```

**Comment by t3mi** [comment]
Another suggestion - to have separate property under schema with lazy evaluation of expressions similar to terraform `locals` which could be computed once all values are available:

```yaml
schema:
  locals:
    fqdn: "${schema.spec.customDomain.id}.${schema.spec.baseDomain}"
```
