### ISSUE TITLE
Changes/updates to instances do not propagate to underlying resources

### ISSUE THREAD

**Issue by amirahav** [awslabs/kro#166]
### Description

**Observed Behavior**:
When the configuration of an instance is modified, the changes do not propagate to the resources managed by the controller.

**Expected Behavior**:
Configuration changes to instances propagate to the resources created for the given instance.

**Reproduction Steps** (Please include `ResourceGroup` and `Instances` files):
using the pod identity `ResourceGroup` example [here](https://github.com/awslabs/kro/blob/main/examples/podidenity/rg.yaml)
And this instance (note that the instance in the [example](https://github.com/awslabs/kro/blob/main/examples/podidenity/instance.yaml)  is invalid:
```
apiVersion: kro.run/v1alpha1
kind: PodIdentity
metadata:
  name: krodemo
spec:
  name: krodemo-11223344
  policyARN: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
```

Will result with following ACK Role resource:
```
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  namespace: kro
spec:
  ...
  policies:
  - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
status:
  ...
```

Changing the `policyARN` value to any other policy (eg `arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess`) or to any other string will result with the instance being updated, however the ACK Role resource will not be updated.

**Versions**:
- kro version: 0.1.0
- Kubernetes Version (`kubectl version`): v1.31.2-eks-7f9249a

**Involved Controllers**:
- Controller URLs and Versions (if applicable):

**Error Logs** (if applicable)**:
```
Paste any relevant logs here
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
