### ISSUE TITLE
Service Account impersonation for ResourceGroup instance execution

### ISSUE THREAD

**Issue by a-hilaly** [awslabs/kro#23]
Symphony currently operates with a single set of credentials across all ResourceGroups, limiting fine grained access control and flexibility in multi tenant or multi enviroment scenarios...

@ellistarn  had the great idea of adding a `serviceAccountName` field in the ResourceGroup spec, allowing the controller to switch to a different `ServiceAccount` when reconciling the "ResourceGroup instance resources"/executing the DAG. This will allow users to instruct Symphony to pick different credentials than the default ones. This is a bit similar to how AWS sts::AssumeRole works, K8s::AssumeServiceAccount :)

Example:
```yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: something.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: Something
  definition:
    spec:
      name: string
  serviceAccount:
    name: service-account-to-assume
  resources: [ ... ]
```

this feature could be extended to incorporate RBAC permission checks during the `ResourceGroup` verification process - symphony can report in advance whether it has the write permissions to operate the described resources.
