### ISSUE TITLE
Support test fixtures for creating ResourceGraphDefinitions

### ISSUE THREAD

**Issue by fsommar** [awslabs/kro#418]
### Feature Description

**Problem Statement**:

Creating a new ResourceGraphDefinition for non-trivial resources requires a lot of iterative work, trying things out. The more conditionals are included, the harder it is to validate that each input creates valid output. Applying an RGD to the cluster, waiting for the status to show up and validate and then create an instance, only to delete them and redo it (until proper lifecycle support is in place) is a slow process.

**Proposed Solution**:

I'm going to [take inspiration from kubebuilder-declarative-pattern](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/tree/d7eaf43a0e1a11fcad6a56157e2499cecef201da/examples/guestbook-operator/controllers/tests) and [Kyverno](https://kyverno.io/docs/kyverno-cli/usage/test/), and suggest support for test fixtures that takes an RGD instance and the expected expansion as input and validates it. I don't have strong opinions on the exact implementation of it, so what I'm suggesting below is very much up for discussion.

Given the definition of an RGD `rgd.yaml`:

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: example
spec:
  schema:
    apiVersion: v1alpha1
    kind: Example
    spec:
      foo: string | required

  resources:
    - id: cm
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${schema.metadata.name}-cm
        data:
          foo: ${schema.spec.foo}
    - id: cm2
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ${schema.metadata.name}-cm2
        data:
          bar: ${schema.spec.foo}
```

I want to be able to create a file `tests/happy.yaml`:

```yaml
apiVersion: tests.kro.run/v1alpha1
kind: Expectations
spec: {}
---
apiVersion: kro.run/v1alpha1
kind: Example
metadata:
  name: foobar
  namespace: sparkles
spec:
  foo: hello world!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foobar-cm
  namespace: sparkles
data:
  foo: hello world!
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foobar-cm2
  namespace: sparkles
data:
  bar: hello world!
```

and a file `tests/sad.yaml`

```yaml
apiVersion: tests.kro.run/v1alpha1
kind: Expectations
spec:
  result: Failure
  message:
    contains: foo is a required field
---
apiVersion: kro.run/v1alpha1
kind: Example
metadata:
  name: foobar
  namespace: sparkles
spec: {}
```

And then validate it with a CLI that points to the RGD on disk:

```bash
kro test -f rgd.yaml tests/
```

**Alternatives Considered**:

The implementation isn't necessarily the important part here, but rather the property of having easy access to a local iterative validation workflow. The tests themselves could also be written in a DSL or a native language, but that requires embedding a runtime and detracts a bit from the relative (ostensible?) simplicity of creating an RGD.

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment
