### ISSUE TITLE
Cluster Scoped Resources supported?

### ISSUE THREAD

**Issue by nabuskey** [awslabs/kro#44]
Looks like cluster resources are not supported as of now. Is this something we want to support?

Repro Steps:

RG:
```yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: deploymentservice.x.symphony.k8s.aws
  namespace: ns1
spec:
  apiVersion: v1alpha1
  kind: DeploymentServiceTest
  definition:
    spec:
      name: string
      namespace: string | default=default
  resources:
  - name: clusterrole
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: pod-reader
      rules:
        - apiGroups: [ "" ]
          resources: [ "pods" ]
          verbs: [ "get", "watch", "list" ]
```

instance:

```yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: DeploymentServiceTest
metadata:
  name: my-deployment-and-service3
  namespace: ns1
spec:
  name: app3
  namespace: ns1
```

Result:
```
Status:
  Conditions:
    Last Transition Time:  2024-10-04T11:30:43-07:00
    Message:               failed to create resource: the server could not find the requested resource
    Observed Generation:   1
    Reason:                ReconciliationFailed
    Status:                False
    Type:                  InstanceSynced
    Last Transition Time:  2024-10-04T11:30:43-07:00
    Message:               Resource clusterrole sync failed: failed to create resource: the server could not find the requested resource
    Observed Generation:   1
    Reason:                Resource sync failed
    Status:                False
    Type:                  ResourceSynced
  State:                   ERROR
```

Looked into this a bit. Looks like it's related to the way the dynamic client constructs the URL and how it's configured.

https://github.com/kubernetes/client-go/blob/ca4a13f6dec7cb79cfd85df0ab3d7cfd05c5c5e9/dynamic/simple.go#L462-L481

The problem is the NS field. It sends it to the wrong endpoint on the API server.

https://github.com/aws-controllers-k8s/private-symphony/blob/2a74a060e292602e58b6b46d41f02923059a232d/internal/controller/instance/controller_reconcile.go#L186
