### ISSUE TITLE
Parser support for defaults

### ISSUE THREAD

**Issue by michaelhtm** [awslabs/kro#45]
Add support for default empty strings in parser.

Eg:
```yaml
spec:
  logging: string | default=""
```

**Comment by newtondev** [comment]
Hi @michaelhtm , this does seem to work for empty string with default value.

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: my-application
spec:
  # kro uses this simple schema to create your CRD schema and apply it
  # The schema defines what users can provide when they instantiate the RG (create an instance).
  schema:
    #group: newtondev.nl
    apiVersion: v1alpha1
    kind: Application
    spec:
      # Spec fields that users can provide.
      name: string
      description: string | default=""
      image: string | default="nginx"
    status:
      # Fields the controller will inject into instances status.
      deploymentConditions: ${deployment.status.conditions}
      availableReplicas: ${deployment.status.availableReplicas}

 # Define the resources this API will manage.
  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name} # Use the name provided by user
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: ${schema.spec.name}
                  image: ${schema.spec.image} # Use the image provided by user
                  env:
                    - name: DESCRIPTION
                      value: "my description :${schema.spec.description}: plus more"
                    - name: OTHER
                      value: ""
                  ports:
                    - containerPort: 80
````

Deployment `kubectl get deploy/my-awesome-app -o yaml`:

```
...

template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-awesome-app
    spec:
      containers:
      - env:
        - name: DESCRIPTION
          value: 'my description :: plus more'
        - name: OTHER
        image: nginx
        imagePullPolicy: Always
        name: my-awesome-app
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
...
```
