### ISSUE TITLE
CEL evaluation should be skipped when includeWhens resolves to false

### ISSUE THREAD

**Issue by joshuabaird** [awslabs/kro#509]
### Description

**Observed Behavior**:
Given a _ResourceGraphDefinition_ that includes the following resource:

```
  resources:
    - id: podidentityassociation
      includeWhen: 
        - ${schema.spec.podIdentity.enabled}
      template:
        apiVersion: eks.services.k8s.aws/v1alpha1
        kind: PodIdentityAssociation
        metadata:
          name: ${schema.spec.resourceName}
        spec: 
          clusterName: ${schema.spec.podIdentity.clusterName} 
          roleARN: ${role.status.ackResourceMetadata.arn}
          serviceAccount: ${schema.spec.podIdentity.serviceAccount}
          namespace: ${schema.metadata.namespace}   
```

and an instance of this RGD that sets `spec.podIdentity` to `false`:

```
apiVersion: kro.run/v1alpha1
kind: ApplicationIAM
metadata:
  name: test-service-2-eso
spec:
  ...
  podIdentity:
    enabled: false
```

The controller complains that `spec.podIdentity.{clusterName|roleARN|serviceAccount}` are not defined:

```
ERROR	dynamic-controller	Error syncing item, requeuing with rate limit	{"item": {"NamespacedKey":"test-service/test-service-2-eso","GVR":{"Group":"kro.run","Version":"v1alpha1","Resource":"applicationiams"}}, "error": "failed to create runtime resource graph definition: failed to evaluate static variables: failed evaluating expression schema.spec.podIdentity.clusterName: no such key: clusterName"}
```

**Expected Behavior**:
Because `spec.podIdentity` is set to `false` -- the user should not have to define `spec.podIdentity.{clusterName|roleARN|serviceAccount}` and the controller should not error.  CEL evaluation should be skipped when `includeWhens` resolves to `false`.

**Versions**:
- kro version: 0.2.2
- Kubernetes Version (`kubectl version`): 1.32

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by a-hilaly** [comment]
@joshuabaird are you still seeing this with 0.7.0?

**Comment by Denyme24** [comment]
hey @a-hilaly. if you're currently not working on this issue, i would like to take this up.

root cause ->  `GetDesired()` evaluates all template CEL expressions before checking if the resource should be ignored, causing "no such key" errors when `includeWhen` is false and optional fields are undefined.

fix ->  Add an early check in `GetDesired()` (pkg/runtime/node.go) to skip CEL evaluation entirely for ignored resources - similar to how we already skip readiness gating for instance nodes.

i've reproduced the issue and validated the fix works.

**Comment by a-hilaly** [comment]
@Denyme24 I'm not sure this is still an issue with kro, currently we call `IsIgnored` before calling `GetDesired`, checkout https://github.com/kubernetes-sigs/kro/blob/main/pkg/controller/instance/resources.go#L192-L216

can you please try to reproduce first and publish your findings in here? If it is indeed still an issue please go ahead and pick it up (you can comment /assign so that the prow bot assigns the github issue for you).

**Comment by Denyme24** [comment]
@a-hilaly, thanks for pointing that out! you're correct that `processNode()` checks `IsIgnored()` before `GetDesired()`.

however, i successfully reproduced the issue. The problem occurs **inside `GetDesired()` itself** at lines 110-123 where it checks `dep.IsReady()` for all dependencies. When a dependency's `readyWhen` expression references fields that don't exist (because the parent resource has `includeWhen=false`), it fails with "no such key" **before** the controller's `IsIgnored()` check can prevent the call.

we can add an early `IsIgnored()` check at the start of `GetDesired()` (after cache check, before dependency readiness check) to skip CEL evaluation entirely for ignored resources.

/assign

**Comment by a-hilaly** [comment]
>however, i successfully reproduced the issue

@Denyme24  can you describe exactly how were you able to reproduce? as in share manifests and steps to go through + description of expected vs current behaviour.

**Comment by Denyme24** [comment]
> > however, i successfully reproduced the issue
> 
> [@Denyme24](https://github.com/Denyme24) can you describe exactly how were you able to reproduce? as in share manifests and steps to go through + description of expected vs current behaviour.

@a-hilaly sure! here's how i reproduced the issue:

## Reproduction Steps

### 1. ResourceGraphDefinition with includeWhen and nested field references

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: test-rgd
spec:
  resources:
    - id: podidentityassociation
      includeWhen: 
        - ${schema.spec.podIdentity.enabled}
      template:
        apiVersion: eks.services.k8s.aws/v1alpha1
        kind: PodIdentityAssociation
        metadata:
          name: ${schema.spec.resourceName}
        spec: 
          clusterName: ${schema.spec.podIdentity.clusterName}
          serviceAccount: ${schema.spec.podIdentity.serviceAccount}
```

### 2. Instance with includeWhen=false and missing nested fields

```yaml
apiVersion: kro.run/v1alpha1
kind: TestRGD
metadata:
  name: test-instance
spec:
  resourceName: my-resource
  podIdentity:
    enabled: false
    # Note: clusterName and serviceAccount are NOT defined
```

### 3. Expected Behavior

since `podIdentity.enabled = false`, the resource should be completely ignored and CEL evaluation of template fields should be skipped. Users shouldn't need to define `clusterName` or `serviceAccount` when the feature is disabled.

### 4. Current Behavior (Bug)

when `GetDesired()` is called (even though controller checks `IsIgnored()` first), it fails evaluating template expressions:

```
failed evaluating expression schema.spec.podIdentity.clusterName: no such key: clusterName
```

## Test Results

i created an automated test in `pkg/runtime/node_includeWhen_bug_test.go` that demonstrates the issue:

### Before Fix:
```
=== RUN   TestBugReproducer_GetDesiredWithMissingStaticVariables
    node_includeWhen_bug_test.go:356: Step 1: Checking IsIgnored()...
    node_includeWhen_bug_test.go:358:   ✅ IsIgnored() = true, err = <nil>
    
    node_includeWhen_bug_test.go:363: Step 2: Calling GetDesired()...
    node_includeWhen_bug_test.go:371:   ❌ GetDesired() failed with error: data pending
    
    Error: "data pending" does not contain "no such key"
    Expected 'no such key' error when accessing undefined clusterName
    
    🐛 BUG REPRODUCED!
    GetDesired() evaluated static variables even though includeWhen=false
    This caused 'no such key: clusterName' error (wrapped as ErrDataPending)
--- FAIL: TestBugReproducer_GetDesiredWithMissingStaticVariables (0.00s)
```

### After Fix:
```
=== RUN   TestBugReproducer_GetDesiredWithMissingStaticVariables
    node_includeWhen_bug_test.go:356: Step 1: Checking IsIgnored()...
    node_includeWhen_bug_test.go:358:   ✅ IsIgnored() = true, err = <nil>
    
    node_includeWhen_bug_test.go:363: Step 2: Calling GetDesired()...
    node_includeWhen_bug_test.go:386:   ✅ GetDesired() succeeded: 0 resources
    
    ✅ BUG FIXED!
    GetDesired() checked IsIgnored() and skipped CEL evaluation
    Returned empty result without evaluating template expressions
    User does NOT need to define podIdentity.clusterName when enabled=false
--- PASS: TestBugReproducer_GetDesiredWithMissingStaticVariables (0.00s)
```

## Root Cause & Fix

while the controller in `resources.go:192-203` correctly checks `IsIgnored()` before calling `GetDesired()`, the issue can still occur if `GetDesired()` is called through other code paths (like dependency resolution).

**fix:** Added an early `IsIgnored()` check at the start of `GetDesired()` in node.go to skip CEL evaluation entirely for ignored resources, making it safe to call regardless of the code path.
