### ISSUE TITLE
Support includesWhen on non-bool types

### ISSUE THREAD

**Issue by joshuabaird** [awslabs/kro#571]
### Feature Description

**Problem Statement**:
I would like to use `includesWhen` to include resources on the presence of a non-bool field in the schema.

For example:

```
spec:
  schema:
    apiVersion: v1alpha1
    kind: ApplicationIAM
    spec:
      name: string
      resourceName: string
      description: string
      role:
        maxSessionDuration: integer | default=3600
        assumeRolePolicyDocument: string
      policy:
        attached:
          arns: "[]string" 
        inline:
          policyDocument: string

resources:
  - id: role
     includeWhen:
       - ${schema.policy.attached}
```

Doing this currently results in this error:
```
failed to validate resource CEL expressions: failed to ensure resource policy includeWhen expressions: output of includeWhen expression schema.spec.policy.attached can only be of type bool
```

**Alternatives Considered**:
Add a `spec.policy.attached.enabled` boolean and test on that.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue
* If you are interested in working on this feature, please leave a comment
