### ISSUE TITLE
Add status field to RGIs

### ISSUE THREAD

**Issue by candonov** [awslabs/kro#71]
Currently RGs provide more information:
``` 
k get rg rds.x.symphony.k8s.aws 
NAME                                APIVERSION   KIND   STATE    TOPOLOGICALORDER                                                            AGE
rds.x.symphony.k8s.aws              v1alpha1    rds      ACTIVE   ["dbinstance","dbsubnetgroup","secret","securitygroup"]    1d
```
RGIs just provide NAME and AGE
```
k get rds.x.symphony.k8s.aws   
NAME         AGE
test          1d
```
Expose status and possibly more information from the status (condition type or reason).

**Comment by a-hilaly** [comment]
Recent symphony versions now inject default fields for instances as well :)

<img width="351" alt="Screenshot 2024-10-29 at 8 13 43 PM" src="https://github.com/user-attachments/assets/caad06ba-3ca7-4f89-919a-fda6422fa8b8">

**Comment by a-hilaly** [comment]
I think we could also support adding custom fields like
```yaml
spec:
  definition:
      spec:
         name: string
         replicas: integer | print=true
         serviceEnable: integer | print=true
```
