### ISSUE TITLE
feat: Add metadata reference

### ISSUE THREAD

**Issue by candonov** [awslabs/kro#75]
Instead of passing explicit variable for the spec.namespace, I'd like to have the resource created in the ns where I instantiate it in. 
``` 
- name: deployment
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${spec.name}
        namespace: ${spec.namespace}
```
do
``` 
- name: deployment
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${spec.name}
        namespace: ${metadata.namespace}
```
Not currently working, rg is inactive, status:
```
    reason: |-
      ReconcileGraphError: ReconcileGraphError: failed to validate resource CEL expressions: failed to dry-run expression metadata.namespace: failed to compile expression: ERROR: <input>:1:1: undeclared reference to 'metadata' (in container '')
       | metadata.namespace
       | ^
```
