### ISSUE TITLE
feat: conditional on the partial resource

### ISSUE THREAD

**Issue by candonov** [awslabs/kro#77]
Currently there are conditional on the whole resource only. Can we have 'partial' conditions like: 
```
    deployment:
    ...     
        spec:
            serviceAccountName: ${serviceaccount.metadata.name}
            containers:
            - name: ${spec.name}
              image: ${spec.image}
              imagePullPolicy: Always
              ports:
              - containerPort: ${spec.port}
         beginifblock: ${s3.enabled == false}
              env:
              - name: S3_BUCKET_NAME
                value: ${s3bucket.metadata.name}
        endifblock
```
or
```
    deployment:
    ...     
        spec:
            serviceAccountName: ${serviceaccount.metadata.name}
            containers:
            - name: ${spec.name}
              image: ${spec.image}
              imagePullPolicy: Always
              ports:
              - containerPort: ${spec.port}
         if: ${s3.enabled == false} | omit 3
              env:
              - name: S3_BUCKET_NAME
                value: ${s3bucket.metadata.name}
```

**Comment by a-hilaly** [comment]
We won't be able to support this unfortunetly, `kro` templating language is very different from Jinja/Go templating.

**Comment by joshuabaird** [comment]
@a-hilaly Bringing this back up because I do think this would be a valuable feature.

Without this, I believe a user is left to create mutually exclusive variant resources:

```
spec:
  schema:
    apiVersion: v1alpha1
    kind: ApplicationIAM
    spec:
      policy:
        attached:
          enabled: boolean | default=false
          arns: "[]string" # a list of IAM policy ARNs to attach to the role
        inline:
          enabled: boolean | default=true
          policyDocument: string | description="A custom IAM policy to attach to the role"

  resources:
    - id: roleWithAttachedPolicy
       includeWhen:
         - ${schema.spec.policy.attached.enabled}
    - id: roleWithInlinePolicy
       includeWhen:
         - ${schema.spoec.policy.inline.enabled}
   ```

In this example, a "role" can only have either an _attached_ or _inline_ policy, not both, so a user is forced to define two mutually exclusive resources.

The problem with this is that it breaks our ability to properly use and track _status_, eg:

```
resources:
  - id: podIdentity
    template:
      ...
      spec:
        roleARN: ${roleX.status.ackResourceMetadata.arn}
```

I don't believe there is a way to specify which "role" resource to use here (see, `roleX`).

**Comment by michaelhtm** [comment]
@joshuabaird You should be able to use ternary operation..this would require you to pre-define the Inline Policy somewhere else tho..
```yaml
spec:
  schema:
    apiVersion: v1alpha1
    kind: ApplicationIAM
    spec:
      policy:
        attached:
          enabled: boolean | default=false
          arns: "[]string" # a list of IAM policy ARNs to attach to the role
        inline:
          enabled: boolean | default=true
          policyDocument: map[string]string | description="A custom IAM policy to attach to the role" # This should be map[string]string?

  resources:
    - id: role
      template:
        ...
        spec:
          ...
          policies: ${schema.spec.policy.attached.enabled ? schema.spec.policy.attached.arns : null}
          inlinePolicies: ${schema.spec.policy.inline.enabled ? schema.spec.policy.inline.policyDocument : null}
```
Would this work for your use case?
