### ISSUE TITLE
add simpleschema short spec types (int and bool)

### ISSUE THREAD

**Issue by candonov** [awslabs/kro#78]
Provide short version for spec types:
`integer` -> `int`
`boolean` -> `bool`

**Comment by newtondev** [comment]
Hi @a-hilaly , I have added the change and a test. Also confirm that it is working using the manifest as follows:

```yaml
apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: my-application
spec:
  schema:
    apiVersion: v1alpha1
    kind: Application
    spec:
      # Spec fields that users can provide.
      name: string
      image: string | default="nginx"
      service:
        port: int | default=80
      ingress:
        enabled: bool | default=false
    status:
      # Fields the controller will inject into instances status.
      deploymentConditions: ${deployment.status.conditions}
      availableReplicas: ${deployment.status.availableReplicas}
---
<remaining resources omitted>

- id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}-service
        spec:
          selector: ${deployment.spec.selector.matchLabels} # Use the deployment selector
          ports:
            - protocol: TCP
              port: ${schema.spec.service.port}
              targetPort: 80

    - id: ingress
      includeWhen:
        - ${schema.spec.ingress.enabled} # Only include if the user wants to create an Ingress

<remaining resources omitted>      
```

```yaml
apiVersion: kro.run/v1alpha1
kind: Application
metadata:
  name: my-application-instance
spec:
  name: my-awesome-app
  ingress:
    enabled: false
  service: {}
```
