### ISSUE TITLE
bug: conditionals not working

### ISSUE THREAD

**Issue by candonov** [awslabs/kro#79]
```
    spec:
      service:
        enabled: boolean | default=true
      ingress:
        enabled: boolean | default=false
...
  - name: service
    conditional:
    - ${spec.service.enabled}
...
  - name: ingress
    conditional:
    - ${spec.ingress.enabled}
```
instance skips both:
```
❯ k describe s3podidentities.x.symphony.k8s.aws test
...
    Message:               Resource ingress synced successfully. status: SKIPPED
    Observed Generation:   1
    Reason:                Resource synced successfully
    Status:                True
    Type:                  ResourceSynced
    Last Transition Time:  2024-11-01T18:08:31Z
    Message:               Resource service synced successfully. status: SKIPPED
    Observed Generation:   1
    Reason:                Resource synced successfully
    Status:                True
    Type:                  ResourceSynced
```
