### ISSUE TITLE
bug: when passing value to deployment via serviceaccount.metadata.name, podidentity doesn't work

### ISSUE THREAD

**Issue by candonov** [awslabs/kro#81]
Create SA and deployment via resource group, :
```
  - name: serviceaccount
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: ${spec.name}
        namespace: ${spec.namespace}
...
- name: deployment
...
          spec:
            serviceAccountName: ${serviceaccount.metadata.name}
```
Create role, policy, and podidentityassocialtion.
Create instance, check the pod spec. It seems that the name of the serviceaccount propagated OK. Exec into the pod and run
```
env | grep AWS
```
There is nothing (there are no env var starting with AWS_, there should be).

Delete instance and RG, change `serviceAccountName: ${spec.name}` instead of `${serviceaccount.metadata.name}`, repeat the steps above, you get: 
```
# env | grep AWS
AWS_STS_REGIONAL_ENDPOINTS=regional
AWS_DEFAULT_REGION=us-east-1
AWS_CONTAINER_CREDENTIALS_FULL_URI=http://169.254.170.23/v1/credentials
AWS_REGION=us-east-1
AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE=/var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
```
Which is the expected behavior.
