### ISSUE TITLE
bug: cannot delete resourcegroup when graph is faulty

### ISSUE THREAD

**Issue by candonov** [awslabs/kro#82]
To reproduce, create a ResourceGroup with a faulty graph:
1. create rg:
```
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: s3podidentity.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: S3PodIdentity
  definition:
    spec:
      name: string
      namespace: string | default="default"
      region: string | default="us-east-1"
      clusterName: string | default="symphony"
      serviceAccount: string | required
 
  - name: podidentityassociation
    definition:
      apiVersion: eks.services.k8s.aws/v1alpha1
      kind: PodIdentityAssociation
      metadata:
        name: ${spec.name}
      spec:
        clusterName: ${spec.clusterName}
        namespace: ${spec.namespace}
        roleARN: ${s3role.status.ackResourceMetadata.arn} #provide any role
        serviceAccount: ${spec.serviceaccount}
```
kubectl apply, you get resource group with faulty graph:
```
❯ k get rg s3podidentity.x.symphony.k8s.aws
NAME                               APIVERSION   KIND            STATE      AGE
s3podidentity.x.symphony.k8s.aws   v1alpha1     S3PodIdentity   Inactive   3s
```
error message:
```
❯ k describe rg s3podidentity.x.symphony.k8s.aws
...
    Reason:                ReconcileGraphError: ReconcileGraphError: failed to validate resource CEL expressions: failed to dry-run expression spec.serviceaccount: failed to evaluate expression: no such key: serviceaccount
    Status:                False
```
Note `${spec.serviceaccount}` is lower case `a`.

Now, delete the resource group:
```
k delete rg s3podidentity.x.symphony.k8s.aws
```
it is hanging, you have to edit the finalizer to delete.
