### ISSUE TITLE
Defaults do not work for nested fields

### ISSUE THREAD

**Issue by iamahgoub** [awslabs/kro#9]
The controller is failing to create an instance of a resource group because of missing fields in the instance, although these missing fields have defaults in the resource group.

The issue seems to be happening when the defaulted fields are nested, and the parent field is not added to the instance (all the nested fields have default in this case).

Instance:
``` yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: cluster-4-with-vpc
spec:
    name: cluster-4-with-vpc
    region: us-west-2
    k8sVersion: '1.30'
    nodesCount: 3
```

Instance with status:
``` yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: EksclusterWithVpc
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"x.symphony.k8s.aws/v1alpha1","kind":"EksclusterWithVpc","metadata":{"annotations":{},"name":"cluster-4-with-vpc","namespace":"default"},"spec":{"k8sVersion":"1.30","name":"cluster-4-with-vpc","nodesCount":3,"region":"us-west-2"}}
  creationTimestamp: "2024-09-16T23:32:37Z"
  generation: 5
  name: cluster-4-with-vpc
  namespace: default
  resourceVersion: "34258924"
  uid: 35c7ff92-9323-48a8-aeac-cd00f111ce56
spec:
  k8sVersion: "1.30"
  name: cluster-4-with-vpc
  nodesCount: 3
  region: us-west-2
status:
  conditions:
  - lastTransitionTime: "2024-09-16T23:33:10Z"
    message: 'no such key: cidr'
    reason: 'no such key: cidr'
    status: "False"
    type: ResourceSynced
  state: ERROR
```

Resource groups:
``` yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: eksclusterwithvpc.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: EksclusterWithVpc
  definition:
    spec:
      name: string
      region: string
      cidr:
        vpcCidr: string | default="10.0.0.0/16"
        publicSubnet1Cidr: string | default="10.0.1.0/24"
        publicSubnet2Cidr: string | default="10.0.2.0/24"
        privateSubnet1Cidr: string | default="10.0.11.0/24"
        privateSubnet2Cidr: string | default="10.0.12.0/24"
      k8sVersion: string
      nodesCount: integer
  resources:
  - name: vpc
    definition:
      apiVersion: x.symphony.k8s.aws/v1alpha1
      kind: Vpc
      metadata:
        name: ${spec.name}
      spec:
        name: ${spec.name}
        region: ${spec.region}
        cidr:
          vpcCidr: ${spec.cidr.vpcCidr}
          publicSubnet1Cidr: ${spec.cidr.publicSubnet1Cidr}
          publicSubnet2Cidr: ${spec.cidr.publicSubnet2Cidr}
          privateSubnet1Cidr: ${spec.cidr.privateSubnet1Cidr}
          privateSubnet2Cidr: ${spec.cidr.privateSubnet2Cidr}
  - name: eks
    definition:
      apiVersion: x.symphony.k8s.aws/v1alpha1
      kind: EksCluster
      metadata:
        name: ${spec.name}
      spec:
          name: ${spec.name}
          region: ${spec.region}
          subnets:
            controlplane:
              subnet1ID: ${vpc.status.privateSubnet1ID}
              subnet2ID: ${vpc.status.privateSubnet2ID}
            workers:
              subnet1ID: ${vpc.status.privateSubnet1ID}
              subnet2ID: ${vpc.status.privateSubnet2ID}
          k8sVersion: ${spec.k8sVersion}
          nodesCount: ${spec.nodesCount}
```

``` yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: ekscluster.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: EksCluster
  definition:
    spec:
      name: string
      region: string
      subnets:
        controlplane:
          subnet1ID: string
          subnet2ID: string
        workers:
          subnet1ID: string
          subnet2ID: string
      k8sVersion: string
      nodesCount: integer
  resources:
  - name: clusterRole
    definition:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        name: ${spec.name}-cluster-role
      spec:
        name: ${spec.name}-cluster-role
        policies:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "eks.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }
  - name: nodeRole
    definition:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        name: ${spec.name}-cluster-node-role
      spec:
        name: ${spec.name}-cluster-node-role
        policies:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "ec2.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }
  - name: ekscluster
    definition:
      apiVersion: eks.services.k8s.aws/v1alpha1
      kind: Cluster
      metadata:
        name: ${spec.name}
      spec:
        name: ${spec.name}
        roleARN: ${clusterRole.status.ackResourceMetadata.arn}
        resourcesVPCConfig:
          endpointPrivateAccess: false
          endpointPublicAccess: true
          subnetIDs:
            - ${spec.subnets.controlplane.subnet1ID}
            - ${spec.subnets.controlplane.subnet2ID}
        #version: ${spec.k8sVersion} a bug needs to be fixed for this to work
  - name: nodegroup
    definition:
      apiVersion: eks.services.k8s.aws/v1alpha1
      kind: Nodegroup
      metadata:
        name: ${spec.name}-nodegroup
      spec:
        name: ${spec.name}-nodegroup
        clusterName: ${spec.name}
        subnets:
          - ${spec.subnets.workers.subnet1ID}
          - ${spec.subnets.workers.subnet2ID}
        nodeRole: ${nodeRole.status.ackResourceMetadata.arn}
        updateConfig:
          maxUnavailable: 1
        scalingConfig:
          minSize: 3 #${spec.nodesCount} a bug needs to be fixed for this to work
          maxSize: 3 #${spec.nodesCount} a bug needs to be fixed for this to work
          desiredSize: 3 #${spec.nodesCount} a bug needs to be fixed for this to work
```

``` yaml
apiVersion: x.symphony.k8s.aws/v1alpha1
kind: ResourceGroup
metadata:
  name: vpc.x.symphony.k8s.aws
spec:
  apiVersion: v1alpha1
  kind: Vpc
  definition:
    spec:
      name: string
      region: string
      cidr:
        vpcCidr: string | default="10.0.0.0/16"
        publicSubnet1Cidr: string | default="10.0.1.0/24"
        publicSubnet2Cidr: string | default="10.0.2.0/24"
        privateSubnet1Cidr: string | default="10.0.11.0/24"
        privateSubnet2Cidr: string | default="10.0.12.0/24"
    status:
      vpcID: ${vpc.status.vpcID}
      publicSubnet1ID: ${publicSubnet1.status.subnetID}
      publicSubnet2ID: ${publicSubnet2.status.subnetID}
      privateSubnet1ID: ${privateSubnet1.status.subnetID}
      privateSubnet2ID: ${privateSubnet2.status.subnetID}
  resources: # how to publish a field in the RG claim e.g. vpcID
  - name: vpc
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: VPC
      metadata:
        name: ${spec.name}-vpc
      spec:
        cidrBlocks: 
        - ${spec.cidr.vpcCidr}
        enableDNSSupport: true
        enableDNSHostnames: true
        tags:
          - key: "Name"
            value: ${spec.name}-vpc
  - name: internetGateway
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: InternetGateway
      metadata:
        name: ${spec.name}-igw
      spec:
        vpc: ${vpc.status.vpcID}
        tags:
          - key: "Name"
            value: ${spec.name}-igw
  - name: natGateway1
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: NATGateway
      metadata:
        name: ${spec.name}-nat-gateway1
      spec:
        subnetID: ${publicSubnet1.status.subnetID}
        allocationID: ${eip1.status.allocationID}
        tags:
          - key: "Name"
            value: ${spec.name}-nat-gateway1
  - name: natGateway2
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: NATGateway
      metadata:
        name: ${spec.name}-nat-gateway2
      spec:
        subnetID: ${publicSubnet2.status.subnetID}
        allocationID: ${eip2.status.allocationID}
        tags:
          - key: "Name"
            value: ${spec.name}-nat-gateway2
  - name: eip1
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: ElasticIPAddress
      metadata:
        name: ${spec.name}-eip1
      spec:
        tags:
          - key: "Name"
            value: ${spec.name}-eip1
  - name: eip2
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: ElasticIPAddress
      metadata:
        name: ${spec.name}-eip2
      spec:
        tags:
          - key: "Name"
            value: ${spec.name}-eip2
  - name: publicRoutetable
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: RouteTable
      metadata:
        name: ${spec.name}-public-routetable
      spec:
        vpcID: ${vpc.status.vpcID}
        routes:
        - destinationCIDRBlock: 0.0.0.0/0
          gatewayID: ${internetGateway.status.internetGatewayID}
        tags:
          - key: "Name"
            value: ${spec.name}-public-routetable
  - name: privateRoutetable1
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: RouteTable
      metadata:
        name: ${spec.name}-private-routetable1
      spec:
        vpcID: ${vpc.status.vpcID}
        routes:
        - destinationCIDRBlock: 0.0.0.0/0
          natGatewayID: ${natGateway1.status.natGatewayID}
        tags:
          - key: "Name"
            value: ${spec.name}-private-routetable1
  - name: privateRoutetable2
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: RouteTable
      metadata:
        name: ${spec.name}-private-routetable2
      spec:
        vpcID: ${vpc.status.vpcID}
        routes:
        - destinationCIDRBlock: 0.0.0.0/0
          natGatewayID: ${natGateway2.status.natGatewayID}
        tags:
          - key: "Name"
            value: ${spec.name}-private-routetable2
  - name: publicSubnet1
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: Subnet
      metadata:
        name: ${spec.name}-public-subnet1
      spec:
        availabilityZone: ${spec.region}a
        cidrBlock: ${spec.cidr.publicSubnet1Cidr}
        mapPublicIPOnLaunch: true
        vpcID: ${vpc.status.vpcID}
        routeTables:
        - ${publicRoutetable.status.routeTableID}
        tags:
          - key: "Name"
            value: ${spec.name}-public-subnet1
          - key: kubernetes.io/role/elb
            value: '1'
  - name: publicSubnet2
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: Subnet
      metadata:
        name: ${spec.name}-public-subnet2
      spec:
        availabilityZone: ${spec.region}b
        cidrBlock: ${spec.cidr.publicSubnet2Cidr}
        mapPublicIPOnLaunch: true
        vpcID: ${vpc.status.vpcID}
        routeTables:
        - ${publicRoutetable.status.routeTableID}
        tags:
          - key: "Name"
            value: ${spec.name}-public-subnet2
          - key: kubernetes.io/role/elb
            value: '1'
  - name: privateSubnet1
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: Subnet
      metadata:
        name: ${spec.name}-private-subnet1
      spec:
        availabilityZone: ${spec.region}a
        cidrBlock: ${spec.cidr.privateSubnet1Cidr}
        vpcID: ${vpc.status.vpcID}
        routeTables:
        - ${privateRoutetable1.status.routeTableID}
        tags:
          - key: "Name"
            value: ${spec.name}-private-subnet1
          - key: kubernetes.io/role/internal-elb
            value: '1'
  - name: privateSubnet2
    definition:
      apiVersion: ec2.services.k8s.aws/v1alpha1
      kind: Subnet
      metadata:
        name: ${spec.name}-private-subnet2
      spec:
        availabilityZone: ${spec.region}b
        cidrBlock: ${spec.cidr.privateSubnet2Cidr}
        vpcID: ${vpc.status.vpcID}
        routeTables:
        - ${privateRoutetable2.status.routeTableID}
        tags:
          - key: "Name"
            value: ${spec.name}-private-subnet2
          - key: kubernetes.io/role/internal-elb
            value: '1'
```
